# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/yanglaoyuan/.local/lib/python3.8/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/yanglaoyuan/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Github/GraphPi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Github/GraphPi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/yanglaoyuan/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/yanglaoyuan/.local/lib/python3.8/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Github/GraphPi/CMakeFiles /mnt/d/Github/GraphPi//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Github/GraphPi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named graph_mining

# Build rule for target.
graph_mining: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graph_mining
.PHONY : graph_mining

# fast build rule for target.
graph_mining/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/graph_mining.dir/build.make src/CMakeFiles/graph_mining.dir/build
.PHONY : graph_mining/fast

#=============================================================================
# Target rules for targets named run_general_tc

# Build rule for target.
run_general_tc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_general_tc
.PHONY : run_general_tc

# fast build rule for target.
run_general_tc/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/run_general_tc.dir/build.make src/CMakeFiles/run_general_tc.dir/build
.PHONY : run_general_tc/fast

#=============================================================================
# Target rules for targets named run_mpi_trivial

# Build rule for target.
run_mpi_trivial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_mpi_trivial
.PHONY : run_mpi_trivial

# fast build rule for target.
run_mpi_trivial/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/run_mpi_trivial.dir/build.make src/CMakeFiles/run_mpi_trivial.dir/build
.PHONY : run_mpi_trivial/fast

#=============================================================================
# Target rules for targets named schedule_printer

# Build rule for target.
schedule_printer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 schedule_printer
.PHONY : schedule_printer

# fast build rule for target.
schedule_printer/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/schedule_printer.dir/build.make src/CMakeFiles/schedule_printer.dir/build
.PHONY : schedule_printer/fast

#=============================================================================
# Target rules for targets named restricts_printer

# Build rule for target.
restricts_printer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 restricts_printer
.PHONY : restricts_printer

# fast build rule for target.
restricts_printer/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/restricts_printer.dir/build.make src/CMakeFiles/restricts_printer.dir/build
.PHONY : restricts_printer/fast

#=============================================================================
# Target rules for targets named asgs_test

# Build rule for target.
asgs_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asgs_test
.PHONY : asgs_test

# fast build rule for target.
asgs_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/asgs_test.dir/build.make test/CMakeFiles/asgs_test.dir/build
.PHONY : asgs_test/fast

#=============================================================================
# Target rules for targets named baseline_test

# Build rule for target.
baseline_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 baseline_test
.PHONY : baseline_test

# fast build rule for target.
baseline_test/fast:
	$(MAKE) $(MAKESILENT) -f tianhe/CMakeFiles/baseline_test.dir/build.make tianhe/CMakeFiles/baseline_test.dir/build
.PHONY : baseline_test/fast

#=============================================================================
# Target rules for targets named in_exclusion_optimize_test

# Build rule for target.
in_exclusion_optimize_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 in_exclusion_optimize_test
.PHONY : in_exclusion_optimize_test

# fast build rule for target.
in_exclusion_optimize_test/fast:
	$(MAKE) $(MAKESILENT) -f tianhe/CMakeFiles/in_exclusion_optimize_test.dir/build.make tianhe/CMakeFiles/in_exclusion_optimize_test.dir/build
.PHONY : in_exclusion_optimize_test/fast

#=============================================================================
# Target rules for targets named all_schedule_test

# Build rule for target.
all_schedule_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_schedule_test
.PHONY : all_schedule_test

# fast build rule for target.
all_schedule_test/fast:
	$(MAKE) $(MAKESILENT) -f tianhe/CMakeFiles/all_schedule_test.dir/build.make tianhe/CMakeFiles/all_schedule_test.dir/build
.PHONY : all_schedule_test/fast

#=============================================================================
# Target rules for targets named performance_test

# Build rule for target.
performance_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 performance_test
.PHONY : performance_test

# fast build rule for target.
performance_test/fast:
	$(MAKE) $(MAKESILENT) -f tianhe/CMakeFiles/performance_test.dir/build.make tianhe/CMakeFiles/performance_test.dir/build
.PHONY : performance_test/fast

#=============================================================================
# Target rules for targets named schedules_test

# Build rule for target.
schedules_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 schedules_test
.PHONY : schedules_test

# fast build rule for target.
schedules_test/fast:
	$(MAKE) $(MAKESILENT) -f tianhe/CMakeFiles/schedules_test.dir/build.make tianhe/CMakeFiles/schedules_test.dir/build
.PHONY : schedules_test/fast

#=============================================================================
# Target rules for targets named code_generator

# Build rule for target.
code_generator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 code_generator
.PHONY : code_generator

# fast build rule for target.
code_generator/fast:
	$(MAKE) $(MAKESILENT) -f tianhe/CMakeFiles/code_generator.dir/build.make tianhe/CMakeFiles/code_generator.dir/build
.PHONY : code_generator/fast

#=============================================================================
# Target rules for targets named unfold_test

# Build rule for target.
unfold_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unfold_test
.PHONY : unfold_test

# fast build rule for target.
unfold_test/fast:
	$(MAKE) $(MAKESILENT) -f tianhe/CMakeFiles/unfold_test.dir/build.make tianhe/CMakeFiles/unfold_test.dir/build
.PHONY : unfold_test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... all_schedule_test"
	@echo "... asgs_test"
	@echo "... baseline_test"
	@echo "... code_generator"
	@echo "... graph_mining"
	@echo "... in_exclusion_optimize_test"
	@echo "... performance_test"
	@echo "... restricts_printer"
	@echo "... run_general_tc"
	@echo "... run_mpi_trivial"
	@echo "... schedule_printer"
	@echo "... schedules_test"
	@echo "... unfold_test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

