# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yanglaoyuan/AsyncSubGraphStorage/GraphPi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yanglaoyuan/AsyncSubGraphStorage/GraphPi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yanglaoyuan/AsyncSubGraphStorage/GraphPi/CMakeFiles /home/yanglaoyuan/AsyncSubGraphStorage/GraphPi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yanglaoyuan/AsyncSubGraphStorage/GraphPi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named merge

# Build rule for target.
merge: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 merge
.PHONY : merge

# fast build rule for target.
merge/fast:
	$(MAKE) -f src/CMakeFiles/merge.dir/build.make src/CMakeFiles/merge.dir/build
.PHONY : merge/fast

#=============================================================================
# Target rules for targets named export_large_graph

# Build rule for target.
export_large_graph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 export_large_graph
.PHONY : export_large_graph

# fast build rule for target.
export_large_graph/fast:
	$(MAKE) -f src/CMakeFiles/export_large_graph.dir/build.make src/CMakeFiles/export_large_graph.dir/build
.PHONY : export_large_graph/fast

#=============================================================================
# Target rules for targets named graph_client

# Build rule for target.
graph_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graph_client
.PHONY : graph_client

# fast build rule for target.
graph_client/fast:
	$(MAKE) -f src/CMakeFiles/graph_client.dir/build.make src/CMakeFiles/graph_client.dir/build
.PHONY : graph_client/fast

#=============================================================================
# Target rules for targets named pattern_match

# Build rule for target.
pattern_match: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pattern_match
.PHONY : pattern_match

# fast build rule for target.
pattern_match/fast:
	$(MAKE) -f src/CMakeFiles/pattern_match.dir/build.make src/CMakeFiles/pattern_match.dir/build
.PHONY : pattern_match/fast

#=============================================================================
# Target rules for targets named generate_update

# Build rule for target.
generate_update: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate_update
.PHONY : generate_update

# fast build rule for target.
generate_update/fast:
	$(MAKE) -f src/CMakeFiles/generate_update.dir/build.make src/CMakeFiles/generate_update.dir/build
.PHONY : generate_update/fast

#=============================================================================
# Target rules for targets named export_graph

# Build rule for target.
export_graph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 export_graph
.PHONY : export_graph

# fast build rule for target.
export_graph/fast:
	$(MAKE) -f src/CMakeFiles/export_graph.dir/build.make src/CMakeFiles/export_graph.dir/build
.PHONY : export_graph/fast

#=============================================================================
# Target rules for targets named graph_mining

# Build rule for target.
graph_mining: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graph_mining
.PHONY : graph_mining

# fast build rule for target.
graph_mining/fast:
	$(MAKE) -f src/CMakeFiles/graph_mining.dir/build.make src/CMakeFiles/graph_mining.dir/build
.PHONY : graph_mining/fast

#=============================================================================
# Target rules for targets named asgs_test

# Build rule for target.
asgs_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 asgs_test
.PHONY : asgs_test

# fast build rule for target.
asgs_test/fast:
	$(MAKE) -f test/CMakeFiles/asgs_test.dir/build.make test/CMakeFiles/asgs_test.dir/build
.PHONY : asgs_test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... merge"
	@echo "... export_large_graph"
	@echo "... graph_client"
	@echo "... pattern_match"
	@echo "... generate_update"
	@echo "... export_graph"
	@echo "... graph_mining"
	@echo "... asgs_test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

